#! /usr/bin/env bash
# vi:ft=sh
FETCH_OUTPUT_DIR=${FETCH_OUTPUT_DIR:-$(dirname $(mktemp --tmpdir -u))}
URL=$(cat | jq --raw-output 'if has("body") then
  .body.url
elif has("url") then
  .url
else
  "error"
end')
if [ "${URL}" = "error" ]; then
  echo "You must provide a URL to download, and I couldn't find one in ${INPUT}" >&2
  exit 1
fi
echo fetching $URL to ${FETCH_OUTPUT_DIR}
aria2c --dir $FETCH_OUTPUT_DIR $URL
